import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from "react-redux";
import Headers from './components/Header';
import Footer from './components/Footer';
const inter = Inter({ subsets: ['latin'] })
import { store } from './app/store';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>

          <Headers />

          {children}

          <Footer />

        </Provider>
      </body>
    </html>
  )
}
